//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace NACSMagazine
{
	/// <summary>
	/// Represents a page of type <see cref="IssuePage"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class IssuePage : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "NACSMagazine.IssuePage";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// Issue.
		/// </summary>
		public Issue Issue { get; set; }


		/// <summary>
		/// ArticleList.
		/// </summary>
		public IEnumerable<Article> ArticleList { get; set; }


		/// <summary>
		/// OtherIssuesList.
		/// </summary>
		public IEnumerable<Issue> OtherIssuesList { get; set; }


		/// <summary>
		/// CurrentFeaturedArticleList.
		/// </summary>
		public IEnumerable<Article> CurrentFeaturedArticleList { get; set; }
	}
}