//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace NACSMagazine
{
	/// <summary>
	/// Represents a content item of type <see cref="Issue"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Issue : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "NACSMagazine.Issue";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// MagazineCover.
		/// </summary>
		public ContentItemAsset MagazineCover { get; set; }


		/// <summary>
		/// MagazineCoverURL.
		/// </summary>
		public string MagazineCoverURL { get; set; }


		/// <summary>
		/// IssueDate.
		/// </summary>
		public DateTime IssueDate { get; set; }


		/// <summary>
		/// DigitalIssueLink.
		/// </summary>
		public string DigitalIssueLink { get; set; }


		/// <summary>
		/// IssueIntro.
		/// </summary>
		public string IssueIntro { get; set; }
	}
}